x = read.csv(file="result_summary/1_sec.dat",head=TRUE,sep="\t")
postscript("result_summary/1_sec.eps")
plot(x$IVCSW+x$VCSW, x$PRTKS, pch=19, xaxt='n', yaxt='n', main='Context Switches (CSws) vs. Program Time (PT) on the 1-second task', xlab='# of CSw', ylab='PT (ticks)')
axt <- seq(min(x$PRTKS),max(x$PRTKS),by=1)
axis(side=2, at=axt, labels=axt)
xaxtl <- seq(min(x$IVCSW+x$VCSW)-10,max(x$IVCSW+x$VCSW)+10,by=10)
axis(side=1, at=xaxtl, labels=xaxtl)
dev.off()
setEPS()

x = read.csv(file="result_summary/1_sec.dat",head=TRUE,sep="\t")
postscript("result_summary/1_sec2.eps")
new_x <- subset(x, x$IVCSW+x$VCSW < max(x$IVCSW+x$VCSW)) 
plot(new_x$IVCSW+new_x$VCSW, new_x$PRTKS, pch=19, xaxt='n', yaxt='n', main='CSws vs. PT on the 1-second task (with the max CSw removed)', xlab='# of CSw', ylab='PT (ticks)')
axt <- seq(min(new_x$PRTKS),max(new_x$PRTKS))
axis(side=2, at=axt, labels=axt)
xaxtl <- seq(min(new_x$IVCSW+new_x$VCSW),max(new_x$IVCSW+new_x$VCSW))
axis(side=1, at=xaxtl, labels=xaxtl)
dev.off()
setEPS()

x = read.csv(file="result_summary/64_sec.dat",head=TRUE,sep="\t")
postscript("result_summary/64_sec.eps")
plot(x$IVCSW+x$VCSW, x$PRTKS, pch=19, xaxt='n', yaxt='n', main='Context Switches (CSws) vs. Program Time (PT) on the 64-second task', xlab='# of CSw', ylab='PT (ticks)')
axt <- seq(min(x$PRTKS),max(x$PRTKS),by=1)
axis(side=2, at=axt, labels=axt)
xaxtl <- seq(min(x$IVCSW+x$VCSW)-20,max(x$IVCSW+x$VCSW)+20,by=20)
axis(side=1, at=xaxtl, labels=xaxtl)
dev.off()
setEPS()

x = read.csv(file="result_summary/64_sec.dat",head=TRUE,sep="\t")
postscript("result_summary/64_sec2.eps")
new_x <- subset(x, x$IVCSW+x$VCSW < max(x$IVCSW+x$VCSW)) 
plot(new_x$IVCSW+new_x$VCSW, new_x$PRTKS, pch=19, xaxt='n', yaxt='n', main='CSws vs. PT on the 64-second task (with the max CSw removed)', xlab='# of CSw', ylab='PT (ticks)')
axt <- seq(min(new_x$PRTKS),max(new_x$PRTKS))
axis(side=2, at=axt, labels=axt)
xaxtl <- seq(min(new_x$IVCSW+new_x$VCSW)-25,max(new_x$IVCSW+new_x$VCSW)+55, by=10)
axis(side=1, at=xaxtl, labels=xaxtl)
dev.off()
setEPS()

x = read.csv(file="result_summary/1024_sec.dat",head=TRUE,sep="\t")
postscript("result_summary/1024_sec.eps")
plot(x$IVCSW+x$VCSW, x$PRTKS, pch=19, xaxt='n', yaxt='n', main='CSws vs. PT on the 1024-second task', xlab='# of CSw', ylab='PT (ticks)')
axt <- seq(min(x$PRTKS)-10,max(x$PRTKS)+10,by=1)
axis(side=2, at=axt, labels=axt)
xaxtl <- seq(min(x$IVCSW+x$VCSW)-100,max(x$IVCSW+x$VCSW)+500,by=240)
axis(side=1, at=xaxtl, labels=xaxtl)
dev.off()
setEPS()

x = read.csv(file="result_summary/1024_sec.dat",head=TRUE,sep="\t")
postscript("result_summary/1024_sec2.eps")
new_x <- subset(x, x$IVCSW+x$VCSW < max(x$IVCSW+x$VCSW)) 
plot(new_x$IVCSW+new_x$VCSW, new_x$PRTKS, pch=19, xaxt='n', yaxt='n', main='CSws vs. PT on the 1024-second task (with the max CSw removed)', xlab='# of CSw', ylab='PT (ticks)')
axt <- seq(min(new_x$PRTKS)-10,max(new_x$PRTKS)+10,by=5)
axis(side=2, at=axt, labels=axt)
xaxtl <- seq(min(new_x$IVCSW+new_x$VCSW),66000, by=20)
axis(side=1, at=xaxtl, labels=xaxtl)
dev.off()
setEPS()
