x = read.csv(file="128_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 1 sec.dat
x = read.csv(file="1_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 2 sec.dat
x = read.csv(file="2_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 4 sec.dat
x = read.csv(file="4_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 8 sec.dat
x = read.csv(file="8_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 16 sec.dat
x = read.csv(file="16_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 32 sec.dat
x = read.csv(file="32_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 64 sec.dat
x = read.csv(file="64_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 800)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 128 sec.dat
x = read.csv(file="128_sec_old.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 256 sec.dat
#### 
x = read.csv(file="256_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 512 sec.dat
#### 
x = read.csv(file="512_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 1024 sec.dat
#### 
x = read.csv(file="1024_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)


### 2048 sec.dat
#### 
x = read.csv(file="2048_sec.dat",head=TRUE,sep="\t")
x <- subset(x, x$ITERNUM <= 10)
#x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 4096 sec.dat
#### 
x = read.csv(file="4096_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 8192 sec.dat
x = read.csv(file="8192_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)

### 16384 sec.dat
x = read.csv(file="16384_sec.dat",head=TRUE,sep="\t")
#x <- subset(x, x$ITERNUM <= 10)
x <- subset(x, x$ITERNUM <= 300)
uol = mean(x$METIME) + 2*sd(x$METIME)
x.sub = subset(x, x$METIME <= uol)
x.ol = subset(x, x$METIME > uol)
nrow(x.sub)
nrow(x.ol)
uol = mean(x.sub$PRTIME) + 2*sd(x.sub$PRTIME)
dol = mean(x.sub$PRTIME) - 2*sd(x.sub$PRTIME)
x.ref = subset(x.sub, x.sub$PRTIME <= uol & x.sub$PRTIME >= dol)
x.ol2 = subset(x.sub, x.sub$PRTIME > uol | x.sub$PRTIME < dol)
nrow(x.ref)
nrow(x.ol2)
min(x.ref$PRTIME)
max(x.ref$PRTIME)
round(mean(x.ref$PRTIME),0)
round(sd(x.ref$PRTIME),1)
sd(x.ref$PRTIME)/mean(x.ref$PRTIME)


