x = read.csv(file="1_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("1_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=max(x$PRTIME)-min(x$PRTIME)+1, plot=F)
plot(h, ylim=c(0,600), freq=TRUE,  xaxt='n', col="green", main='PT frequency on the 1-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(floor(min(h$mids)),ceiling(max(h$mids)))
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=40)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- dgamma(yfit, shape=1.5)
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="2_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("2_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=max(x$PRTIME)-min(x$PRTIME)+1, plot=F)
plot(h, ylim=c(0,600), freq=TRUE,  xaxt='n', col="green", main='PT frequency on the 2-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(floor(min(h$mids))-10,ceiling(max(h$mids))+10)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=40)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="4_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("4_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=max(x$PRTIME)-min(x$PRTIME)+1,plot=F)
plot(h, ylim=c(0,300), freq=TRUE,  xaxt='n', col="green", main='PT frequency on the 4-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-2,max(x$PRTIME)+2)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=40)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="8_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("8_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=max(x$PRTIME)-min(x$PRTIME)+1,plot=F)
plot(h, ylim=c(0,350), freq=TRUE,  xaxt='n', col="green", main='PT frequency on the 8-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-3,max(x$PRTIME)+4)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=40)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="16_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("16_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, plot=F)
plot(h, freq=TRUE,  xaxt='n', col="green", main='PT frequency on the 16-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(floor(min(h$mids)),ceiling(max(h$mids)))
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=40) 
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME)) 
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME) 
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="32_sec.dat",head=TRUE,sep="\t")
x = read.csv(file="32_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("32_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, plot=F)
plot(h, freq=TRUE,  xaxt='n', col="green", main='PT frequency on the 32-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-3,max(x$PRTIME)+4)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=40) 
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME)) 
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME) 
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="64_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("64_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, plot=F)
plot(h, freq=TRUE, ylim=c(0,350),xaxt='n', col="green", main='PT frequency on the 64-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-3,max(x$PRTIME)+4)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=100) 
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME)) 
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME) 
lines(xfit, yfit, col="blue", lwd=2)
dev.off()
x = read.csv(file="128_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("128_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, plot=F)
plot(h, freq=TRUE, ylim=c(0,150), xaxt='n', col="green", main='PT frequency on the 128-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-3,max(x$PRTIME)+4)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=200)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()
x = read.csv(file="256_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("256_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=max(x$PRTIME)-min(x$PRTIME),plot=F)
plot(h, freq=TRUE, ylim=c(0,50), xaxt='n', col="green", main='PT frequency on the 256-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-5,max(x$PRTIME)+5)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=200)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="512_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("512_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=ceiling((max(x$PRTIME)-min(x$PRTIME))/4),plot=F)
plot(h, freq=TRUE, ylim=c(0,200), xaxt='n', col="green", main='PT frequency on the 512-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-30,max(x$PRTIME)+30)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME)-30,max(x$PRTIME)+30,length=200)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="1024_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("1024_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=ceiling((max(x$PRTIME)-min(x$PRTIME))/4),plot=F)
plot(h, freq=TRUE, ylim=c(0,150), xaxt='n', col="green", main='PT frequency on the 1024-second task', xlab='PT (ms)', ylab=expression('Frequency'))
xaxtl <- seq(min(x$PRTIME)-30,max(x$PRTIME)+30)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME)-30,max(x$PRTIME)+30,length=200)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="1024_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("1024_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=ceiling((max(x$PRTIME)-min(x$PRTIME))/4),plot=F)
plot(h, freq=TRUE, ylim=c(0,150), xaxt='n', col="green", main='PT frequency on the 1024-second task', xlab='PT (ms)', ylab=expression('Frequency'))
nb = ceiling((max(h$mids)-min(h$mids))/20)
xaxtl <- seq(min(x$PRTIME)-20,max(x$PRTIME)+20, by=nb)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME)-30,max(x$PRTIME)+30,length=200)
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME))
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME)
lines(xfit, yfit, col="blue", lwd=2)
dev.off()

x = read.csv(file="2048_sec.dat",head=TRUE,sep="\t")
setEPS()
postscript("2048_sec_pt_hist.eps")
h = hist(x$PRTIME, right=F, breaks=ceiling((max(x$PRTIME)-min(x$PRTIME))/4),plot=F)
plot(h, freq=TRUE, ylim=c(0,100),  xaxt='n', col="green", main='PT frequency on the 2048-second task', xlab='PT (ms)', ylab=expression('Frequency'))
nb = ceiling((ceiling(max(h$mids))-floor(min(h$mids)))/20)
xaxtl <- seq(floor(min(h$mids)-10),ceiling(max(h$mids)+10), by=nb)
axis(side=1, at=xaxtl, labels=xaxtl)
xfit<-seq(min(x$PRTIME),max(x$PRTIME),length=200) 
yfit<-dnorm(xfit,mean=mean(x$PRTIME),sd=sd(x$PRTIME)) 
yfit <- yfit*diff(h$mids[1:2])*length(x$PRTIME) 
lines(xfit, yfit, col="blue", lwd=2)
dev.off()


